name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: for dir in day*; do cd $dir; cargo build --verbose; cd ..; done
    - name: Run tests
      run: for dir in day*; do cd $dir; cargo test --verbose; cd ..; done
